default:
	g++ src/main.cpp src/Animation.cpp src/Entity.cpp src/GameState.cpp src/Vec2.cpp src/GameEngine.cpp src/GameState_Play.cpp src/Physics.cpp src/Assets.cpp src/EntityManager.cpp src/GameState_Menu.cpp  -std=c++17 -lsfml-window -lsfml-graphics -lsfml-system -o bin/sfml



